// <auto-generated />
using System;
using ContractIQ.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;
using Pgvector;

#nullable disable

namespace ContractIQ.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ContractIqDbContext))]
    [Migration("20260828204150_AddKnowledgeRetrieval")]
    partial class AddKnowledgeRetrieval
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ContractIQ.Infrastructure.Persistence.Models.CancellationRequestRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("uuid")
                        .HasColumnName("contract_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<DateOnly>("EarliestTerminationDate")
                        .HasColumnType("date")
                        .HasColumnName("earliest_termination_date");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("idempotency_key");

                    b.Property<decimal>("PenaltyAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("penalty_amount");

                    b.Property<string>("PenaltyCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("penalty_currency")
                        .IsFixedLength();

                    b.Property<DateOnly>("RequestedOn")
                        .HasColumnType("date")
                        .HasColumnName("requested_on");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_cancellation_requests");

                    b.HasIndex("ContractId")
                        .IsUnique()
                        .HasDatabaseName("ux_cancellation_requests_open_contract")
                        .HasFilter("status = 1");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_cancellation_requests_customer_id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ux_cancellation_requests_idempotency_key");

                    b.ToTable("cancellation_requests", null, t =>
                        {
                            t.HasCheckConstraint("ck_cancellation_requests_currency", "penalty_currency ~ '^[A-Z]{3}$'");

                            t.HasCheckConstraint("ck_cancellation_requests_dates", "earliest_termination_date >= requested_on");

                            t.HasCheckConstraint("ck_cancellation_requests_penalty_non_negative", "penalty_amount >= 0");

                            t.HasCheckConstraint("ck_cancellation_requests_status", "status IN (1, 2, 3)");
                        });
                });

            modelBuilder.Entity("ContractIQ.Infrastructure.Persistence.Models.ContractRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<decimal>("EarlyTerminationPenaltyRate")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("early_termination_penalty_rate");

                    b.Property<DateOnly>("MinimumCommitmentEndDate")
                        .HasColumnType("date")
                        .HasColumnName("minimum_commitment_end_date");

                    b.Property<decimal>("MonthlyFeeAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("monthly_fee_amount");

                    b.Property<string>("MonthlyFeeCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("monthly_fee_currency")
                        .IsFixedLength();

                    b.Property<int>("NoticePeriodDays")
                        .HasColumnType("integer")
                        .HasColumnName("notice_period_days");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_contracts");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_contracts_customer_id");

                    b.ToTable("contracts", null, t =>
                        {
                            t.HasCheckConstraint("ck_contracts_commitment_dates", "minimum_commitment_end_date >= start_date");

                            t.HasCheckConstraint("ck_contracts_currency", "monthly_fee_currency ~ '^[A-Z]{3}$'");

                            t.HasCheckConstraint("ck_contracts_monthly_fee_non_negative", "monthly_fee_amount >= 0");

                            t.HasCheckConstraint("ck_contracts_notice_period_non_negative", "notice_period_days >= 0");

                            t.HasCheckConstraint("ck_contracts_penalty_rate", "early_termination_penalty_rate >= 0 AND early_termination_penalty_rate <= 1");

                            t.HasCheckConstraint("ck_contracts_status", "status IN (1, 2, 3)");
                        });
                });

            modelBuilder.Entity("ContractIQ.Infrastructure.Persistence.Models.CustomerRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_customers");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_customers_name");

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("ContractIQ.Infrastructure.Persistence.Models.KnowledgeChunkRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ChunkIndex")
                        .HasColumnType("integer")
                        .HasColumnName("chunk_index");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<string>("ContentChecksum")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("content_checksum");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<Vector>("Embedding")
                        .IsRequired()
                        .HasColumnType("vector(768)")
                        .HasColumnName("embedding");

                    b.Property<int>("Page")
                        .HasColumnType("integer")
                        .HasColumnName("page");

                    b.Property<NpgsqlTsVector>("SearchVector")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasColumnName("search_vector")
                        .HasComputedColumnSql("to_tsvector('simple', coalesce(section, '') || ' ' || coalesce(content, ''))", true);

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("section");

                    b.HasKey("Id")
                        .HasName("pk_knowledge_chunks");

                    b.HasIndex("DocumentId", "ChunkIndex")
                        .IsUnique()
                        .HasDatabaseName("ux_knowledge_chunks_document_index");

                    b.ToTable("knowledge_chunks", (string)null);
                });

            modelBuilder.Entity("ContractIQ.Infrastructure.Persistence.Models.KnowledgeDocumentRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentChecksum")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("content_checksum");

                    b.Property<Guid?>("ContractId")
                        .HasColumnType("uuid")
                        .HasColumnName("contract_id");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("DocumentKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("document_key");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("document_type");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date")
                        .HasColumnName("effective_from");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date")
                        .HasColumnName("effective_to");

                    b.Property<string>("EmbeddingModel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("embedding_model");

                    b.Property<DateTimeOffset>("IndexedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("indexed_at_utc");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("language");

                    b.Property<string>("SourcePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("source_path");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_knowledge_documents");

                    b.HasIndex("DocumentKey", "Version")
                        .IsUnique()
                        .HasDatabaseName("ux_knowledge_documents_key_version");

                    b.HasIndex("CustomerId", "ContractId", "EffectiveFrom")
                        .HasDatabaseName("ix_knowledge_documents_scope_effective_from");

                    b.ToTable("knowledge_documents", (string)null);
                });

            modelBuilder.Entity("ContractIQ.Infrastructure.Persistence.Models.CancellationRequestRecord", b =>
                {
                    b.HasOne("ContractIQ.Infrastructure.Persistence.Models.ContractRecord", null)
                        .WithMany()
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cancellation_requests_contracts_contract_id");

                    b.HasOne("ContractIQ.Infrastructure.Persistence.Models.CustomerRecord", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cancellation_requests_customers_customer_id");
                });

            modelBuilder.Entity("ContractIQ.Infrastructure.Persistence.Models.ContractRecord", b =>
                {
                    b.HasOne("ContractIQ.Infrastructure.Persistence.Models.CustomerRecord", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_contracts_customers_customer_id");
                });

            modelBuilder.Entity("ContractIQ.Infrastructure.Persistence.Models.KnowledgeChunkRecord", b =>
                {
                    b.HasOne("ContractIQ.Infrastructure.Persistence.Models.KnowledgeDocumentRecord", "Document")
                        .WithMany("Chunks")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_knowledge_chunks_documents_document_id");

                    b.Navigation("Document");
                });

            modelBuilder.Entity("ContractIQ.Infrastructure.Persistence.Models.KnowledgeDocumentRecord", b =>
                {
                    b.Navigation("Chunks");
                });
#pragma warning restore 612, 618
        }
    }
}
